[workspace]
channels = ["knime/label/nightly", "knime", "conda-forge", "dglteam"]
platforms = ["win-64", "linux-64", "osx-64", "osx-arm64"]

[tasks]

[dependencies]
python = "3.11.*"
knime-extension = ">=5.5.0"
knime-python-base = ">=5.5.0"
tokenizers = "0.20.1.*"
transformers = "4.45.2.*"
pytorch-cpu = ">=2.7.0,<3"
scikit-learn = "1.5.1.*"


[feature.build.dependencies]
python = "3.9.*"
knime-extension-bundling = "5.5.*"

[feature.build.tasks]
build = { args = [{ "arg" = "dest", "default" = "./local-update-site" }], cmd = "python ./.pixi/envs/build/bin/build_python_extension.py . {{ dest }}"}

[environments]
build = {features = ["build"], no-default-feature = true}
